// <auto-generated />
namespace Project.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Initital_Create : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initital_Create));
        
        string IMigrationMetadata.Id
        {
            get { return "202002211021411_Initital_Create"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
